apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coderipper-runner-rb
subjects:
  - kind: ServiceAccount
    name: coderipper-runner-sa
roleRef:
  kind: Role
  name: coderipper-runner-role
  apiGroup: rbac.authorization.k8s.io
