apiVersion: v1
kind: Secret
metadata:
  name: coderipper-secrets
type: Opaque
stringData:
  AUTH_JWT_SECRET: {{ .Values.secrets.authSecret | default "changeme" | quote }}
  BADGE_SERVICE_TOKEN: {{ .Values.secrets.badgeToken | default "devtoken" | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | default "" | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | default "" | quote }}
