apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: coderipper
  name: coderipper-runner-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
