apiVersion: v1
kind: Service
metadata:
  name: coderipper-webhook
  namespace: coderipper
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    app: coderipper-webhook
  type: ClusterIP
